### ISSUE TITLE
Make PyMSG pip installable

### ISSUE THREAD

**Issue by AWehrhahn** [rhdtownsend/msg#11]
Currently there is no automated way to install the software package. This could be fixed by creating a pip compatible setup.py script and uploading the software to pypi.org.

Review Thread: https://github.com/openjournals/joss-reviews/issues/4602

**Comment by rhdtownsend** [comment]
pymsg is now pip-installable, as described in the updated Quick Start and Installation documentation:

https://msg.readthedocs.io/en/latest/user-guide/quick-start.html
file:///Users/townsend/devel/msg/docs/build/html/ref-guide/installation.html

For now, I dont think it makes sense to upload pymsg to the Python Package Index. The module can't function without the MSG libraries, and therefore a user will always have to install MSG as well. It seems wise to therefore ship pymsg with MSG.
