### ISSUE TITLE
Performance claims for large files and additional library support

### ISSUE THREAD

**Issue by ivastar** [rhdtownsend/msg#14]
Claims are made for the handling of the graceful handling of large files. I was unable to verify these claims. Instructions on how to set the cache size and what is a reasonable value relative to the system memory would benefit users. Also not apparent what other libraries are supported and how those libraries can be converted to the format required by MSG. 

Review thread: #https://github.com/openjournals/joss-reviews/issues/4602

**Comment by rhdtownsend** [comment]
Details on cache function, together with a demonstration of caching in action, are provided in a new Data Caching section in the documentation: 

https://msg.readthedocs.io/en/latest/user-guide/data-caching.html

Likewise, a discussion of importing grids from other sources is provided in a new Data Files section:

https://msg.readthedocs.io/en/latest/user-guide/data-files.html

**Comment by rhdtownsend** [comment]
I'm closing this as the functionality is released (from v1.1 onward)
