### ISSUE TITLE
cfitsio install library looking in the wrong spot

### ISSUE THREAD

**Issue by astroJeff** [rhdtownsend/msg#3]
When installing msg, I bug out with the error: 

```
ld: warning: directory not found for option '-L/opt/local/lib'
ld: library not found for -lcfitsio
```

I have the cfitsio library installed, but I cannot find where to tell the make file to look in the correct directory location. Any ideas?

**Comment by astroJeff** [comment]
I was able to hack together a solution whereby I create the missing `/opt/local/lib` directory and copy my install of cfitsio into that, but there ought to be a better way.

**Comment by rhdtownsend** [comment]
Yep, there is -- edit the definition of FITS_LDFLAGS in $MSG_DIR/build/Makefile

**Comment by rhdtownsend** [comment]
I should add that the cfitsio library is only needed during build when TOOLS=yes.

**Comment by astroJeff** [comment]
All good. Sorry for the confusion. Thank you! One very minor point - I had trouble finding this file (I definitely should have found it!) because the documentation all discusses a Makefile in $MSG_DIR/src/build/Makefile.
