### ISSUE TITLE
Kernel dies on pymsg tutorial

### ISSUE THREAD

**Issue by astroJeff** [rhdtownsend/msg#4]
I'm running into another bug here. When going through the Python walkthrough, my kernel dies when running:

```
# Load the SpecGrid
GRID_DIR = os.path.join(MSG_DIR, 'data', 'grids')
specgrid_file_name = os.path.join(GRID_DIR, 'sg-demo.h5')
specgrid = pymsg.SpecGrid(specgrid_file_name)
```

Specifically, the last line is the culprit. Before I start diving into this, do you have any ideas? Because it's cython, such bugs are quite difficult to find.

**Comment by rhdtownsend** [comment]
Funny, it worked this morning! Must have been something I messed up when fixing other issues with the C interface. I'll look into it.

**Comment by rhdtownsend** [comment]
Should be fixed now -- please checkout the latest commit.

**Comment by astroJeff** [comment]
Works perfectly. Thank you!
