### ISSUE TITLE
Kernel dies running PhotGrid

### ISSUE THREAD

**Issue by aaronesque** [rhdtownsend/msg#6]
Running
> sg = pymsg.SpecGrid('sg-demo.h5')

does work, but running
> pg = pymsg.PhotGrid(‘sg-demo.h5’, ‘pb-Kepler-Kepler.K-AB.h5’)

kills the kernel.

**Comment by rhdtownsend** [comment]
Can you post the passband file you're using? I'm guessing it is out of date, but MSG should fail gracefully in that case rather than crashing.

**Comment by aaronesque** [comment]
Here it is-- I'll try using a different passband as well.
[pb-Kepler-Kepler.K-AB.h5.zip](https://github.com/rhdtownsend/msg/files/8735677/pb-Kepler-Kepler.K-AB.h5.zip)

**Comment by rhdtownsend** [comment]
It looks like you're using an old passband file. Can you try downloading a new one from the documentation site?

**Comment by aaronesque** [comment]
I found the issue-- my star's temperature and log(g) exceeded the grid boundary!

**Comment by rhdtownsend** [comment]
That should cause a Python exception, not a kernel crash. So, I’m not sure that was the reason.

On May 23, 2022, at 2:37 PM, Aaron Lopez ***@***.******@***.***>> wrote:



I found the issue-- my star's temperature and log(g) exceeded the grid boundary!
