### ISSUE TITLE
Failure to build 1.0-rc1 release tarball with MESA SDK 21.4.1 on Fedora 36

### ISSUE THREAD

**Issue by warrickball** [rhdtownsend/msg#7]
I just tried to build `1.0-rc1` by following the instructions in the [Quick Start](https://msg.readthedocs.io/en/latest/user-guide/quick-start.html), specifically:
```
$ export MESASDK_ROOT=$HOME/mesa/sdk/21.4.1
$ source $MESASDK_ROOT/bin/mesasdk_init.sh
$ tar -xf ~/Downloads/msg-1.0-rc1.tar.gz # after clicking the release link
$ cd msg-1.0-rc1
$ export MSG_DIR=$(pwd)
$ make -C $MSG_DIR
```
and ran into the error
```
$ make -C $MSG_DIR
make: Entering directory '/home/wball/code/msg/1.0-rc1'
../src/lib/cmsg_m.fypp:18: error: include file 'forum.inc' not found [FyppFatalError]
../src/lib/fmsg_m.fypp:18: error: include file 'forum.inc' not found [FyppFatalError]
../src/lib/msg_m.fypp:18: error: include file 'forum.inc' not found [FyppFatalError]
../src/lib/forum_m.fypp:18: error: include file 'forum.inc' not found [FyppFatalError]
make[1]: *** No rule to make target 'forum_m.f90', needed by 'forum_m.o'.  Stop.
make: *** [Makefile:15: all] Error 2
make: Leaving directory '/home/wball/code/msg/1.0-rc1'
```
I noticed that `forum` is a git submodule in a [separate repo](https://github.com/rhdtownsend/forum). There's an empty folder under `$MSG_DIR/src/forum`, too.
```
$ find . -iname *forum*
./src/forum
./src/lib/forum_m.fypp
./build/.forum_m.dpp
```
The instructions for cloning the git repo and installing the development version do end with a successful build, so I suspect the relevant files from `forum` aren't being correctly included in the GitHub release archive.

**Comment by rhdtownsend** [comment]
Added a link on the release page, and added the troubleshooting item as suggested (on main, will be in the next rc or in the full release).

**Comment by warrickball** [comment]
This all looks good / is working for me, so you're welcome to close this.
